# Generated by Django 2.2.1 on 2019-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pdtname', models.CharField(default='', max_length=70)),
                ('Pdtprice', models.IntegerField(default=1)),
                ('Pdtdesc', models.CharField(blank=True, default='', max_length=70)),
                ('PdtImg', models.ImageField(upload_to='')),
            ],
        ),
    ]
