# Generated by Django 2.2.1 on 2019-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null=False', upload_to=''),
            preserve_default=False,
        ),
    ]
