# Generated by Django 2.2.1 on 2019-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
