# Generated by Django 2.2.1 on 2019-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190622_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=False, upload_to='AngularAPI/img'),
        ),
    ]
